# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenGL_Demos_01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenGL_Demos_01
  pod 'OpenGLLibs' , :path => './../OpenGLLibs'
#
#  pod 'GLSource' , :path => './../GLSource'

  target 'OpenGL_Demos_01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
